Update README with meta doc
http-interop/http-middleware pull request #25
Opened 2016-11-06 16:49 UTC by shadowhand

Importing the meta document from PSR-15 for review and editing.

2016-11-06 16:51 UTC, shadowhand commented
This has been updated heavily to reflect recent decisions regarding naming and scope. Any feedback would be greatly appreciated.

cc @http-interop/http-middleware-contributors

2016-11-10 16:02 UTC, weierophinney requested changes
I've proposed a few wording changes, and then noted some areas that are either slightly contradictory, or which need expansion.

2016-11-10 16:02 UTC, weierophinney commented on README.md
> +The HTTP Messages specification contain any reference to HTTP Middleware.
`s/contain/do not contain/`.

2016-11-10 16:02 UTC, weierophinney commented on README.md
> +The design pattern used by middleware has existed for many years as [pipeline][pipeline],
`s/[pipeline][pipeline]/[the pipeline pattern][pipeline]/`

2016-11-10 16:02 UTC, weierophinney commented on README.md
> +  2. A delegate that receives the request to dispatch next middleware.
`s/dispatch next middleware/dispatch the next middleware in the pipeline/`.

2016-11-10 16:02 UTC, weierophinney commented on README.md
> +handle(Request $request, $type, $catch): Response
This contradicts line 119, where you indicated that the StackPHP "style" is `fn(request, frame): response`. I'm thinking that the narrative at line 119 should likely not mention Stack at all.

2016-11-10 16:02 UTC, weierophinney commented on README.md
> +on client side request processing.
I think this paragraph needs some expansion:

- You gloss over "external requests". Maybe expand to say, "For client-side middleware that makes a request to an external resource, you will typically want to react asychronously...", and then detail *why* async is typical in this situation.
- Why is a "promise of a response" required under async? (*I* know, but not everyone is familiar with async processing.)
- What is a "promise"? (*I* know, but will every reader coming to the spec? Link to the [Promises A+ spec](https://promisesaplus.com/)

2016-11-13 16:01 UTC, mindplay-dk approved these changes

2016-11-13 16:03 UTC, mindplay-dk commented
What I mean by my approval here is, "approved with minor comments", just the minor corrections suggested by @weierophinney.

2016-11-14 02:09 UTC, shadowhand commented on README.md
> +handle(Request $request, $type, $catch): Response
Stack implements has multiple parameters, but none of them are `$response`. As such, I think it still constitutes a widely used example of single-pass.

2016-11-19 13:45 UTC, merged